blank_issues_enabled: true
contact_links:
  - name: Terraform Provider Google Issue Tracking
    url: https://github.com/terraform-providers/terraform-provider-google/issues/new/choose
    about: |
      Please submit issues or here.
